### ISSUE TITLE
Can't Select SKU

### ISSUE THREAD

**Issue by programmerkgit** [microsoft/vscode-azure-blockchain-ethereum#12]
When I try to create consortium, I must select SKU.
But, there is no SKU list, and What is SKU ???
<img width="641" alt="Screen Shot 2019-07-19 at 12 34 44" src="https://user-images.githubusercontent.com/37021071/61543884-49f6f280-aa7f-11e9-9e12-b4e0ba795eca.png">

**Comment by caleteeter** [comment]
Sorry to hear this.  This sounds like a problem getting the ABS instance created.  Can you confirm the region you are looking to deploy this to?  ABS is available in limited regions while in preview.

Another approach could be to deploy the ABS instance via the Azure Portal and then connect to this from VS Code.

**Comment by divya661** [comment]
SIr, I too facing the same problem and  I am using "southeastasia" as my region

**Comment by caleteeter** [comment]
Appreciate the added detail of the region.  I will check this on my end.  Much thanks.

**Comment by caleteeter** [comment]
I did testing and can't reproduce this issue.  I am thinking this has to do with the subscription that is being deployed to.  Can you please create the ABS instance in Azure (https://portal.azure.com/#create/Microsoft.Blockchain).  I would be interested in two things:

1. Can you deploy with the same parameters that you were using directly inside VS Code.
2. Can you connect to this consortum from inside VS Code after deployment via the Azure management portal.

**Comment by divya661** [comment]
Sir, now  I have created the consortium  by suing azure portal link directly, in the required resource group and I had found that consortium mentioned in the blockchain service tab in the vs-code. I have still used the same location. I am using a free-trail subscription.

**Comment by programmerkgit** [comment]
My region was Japan East.
I used free-trial subscription.

1.Can you deploy with the same parameters that you were using directly inside VS Code.
Yes.
2.Can you connect to this consortum from inside VS Code after deployment via the Azure management portal.
Yes

I was trying free plan, and It seems I ran out of free usage in one day.
I cannot check anymore.

**Comment by caleteeter** [comment]
Thanks again for the added detail @divya661 !!  The only variable is the free trial sub (as I used the same regions).  I am checking to see if the resource provider for a subscription (especially a new free trial one) could be the issue.  I will check this out.

Good to hear that you can attach to a consortium once you deployed via the portal.

**Comment by caleteeter** [comment]
Confirmed that I can duplicate with a new free trial account.  I am tracking this down but appears to be another issue, not something controlled by the extension as this works with other accounts.  I will provide the full details here once I get the root cause for these sub types.

As a workaround, feel free to provision new ABS instances via the portal (https://portal.azure.com) and connect to them from the extension.

**Comment by ranjanbinwani** [comment]
Even I was facing the same issue when creating the consortium from the extension with the region selected as "southeastasia", but I was successful in creating the consortium from the Azure portal and connect to it via the extension. 
Hope that this issue is resolved in the near future.

**Comment by rrutiaga** [comment]
I ran into the same issue and I am not using the free trial version of azure.  I am very disappointed since I was following the instructions on the SDK documentation.

**Comment by caleteeter** [comment]
Sorry for the trouble @rrutiaga .  Working on a release of the extension to resolve this.

**Comment by rrutiaga** [comment]
Thank you for working on it.  Is there a place I can post general questions on the azure blockchain service including the workbench?

**Comment by caleteeter** [comment]
For sure @rrutiaga , we have a community site and forum

https://techcommunity.microsoft.com/t5/Blockchain/bd-p/AzureBlockchain
https://social.msdn.microsoft.com/Forums/en-US/home?forum=azureblockchain

**Comment by rrutiaga** [comment]
Great!  Thanks again.

**Comment by caleteeter** [comment]
__UPDATE__: I have been testing the heck out of this from various locations within South East region and other regions, with different accounts, free and otherwise.

We have released a new version of the extension (current is v0.1.7).  Can I have you try this one and let me know if you see the SKUs now.

**Comment by ranjanbinwani** [comment]
The latest version of the extension still seems to be v0.1.7

![image](https://user-images.githubusercontent.com/25248881/63074322-6127e380-bf4a-11e9-893c-9778d9b7ee3f.png)

**Comment by rrutiaga** [comment]
Hi Cale,

I will test it today and let you know the results.  Thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by caleteeter** [comment]
Thanks @ranjanbinwani and @rrutiaga !  I have a backlog item to add more logging to our outbound calls to Azure to capture errors that are potentially being hidden here from us.  Additionally, working with the Azure Blockchain Service team to get this resolved.  Thanks again for helping us track this down.

**Comment by rrutiaga** [comment]
I updated the azure blockchain service extension but I am still not able to create the consortium in azure.  I get to the part where it asks for the name.  It then runs the validating name but stops after that without any error message.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by caleteeter** [comment]
Much thanks @rrutiaga !

**Comment by jimt222** [comment]
Same issue, using Azure Blockchain Development Kit v 0.1.7, East Region .. prompted for SKU and nothing works. 

I tried downgrading Dev Kit to 0.1.6 and 0.1.5 but same problem. Using paid Azure account.

**Comment by caleteeter** [comment]
We have added some bug fixes here, wanted to check with you @jimt222 to see if this is resolved now.

**Comment by caleteeter** [comment]
Closing this as we don't have repros with our current version (0.1.12).  @jimt222 feel free to reopen if you see anything in the latest builds!

**Comment by aah50** [comment]
This issue is still there. Im on version 0.1.13 and trying EU west region. If I try the workaround though the Azure portal, does that incur any charges?

**Comment by caleteeter** [comment]
@aah50 sorry to hear this is still a problem.  I just tested this to West Europe with no issue.  I am wondering if the API call we are making [here](https://github.com/microsoft/vscode-azure-blockchain-ethereum/blob/dc12c4f832818353dec3dbf0766a61b50b1d4da0/src/ARMBlockchain/AzureBlockchainServiceClient.ts#L121) is not returning correctly from your region.  What I can do is source the request from your region (I can test from West Europe datacenter, instead of hitting for US).

To answer your other question, there is no additional charges for provisioning via the portal or via the extension.  The pricing for Basic and Standard are listed [here](https://azure.microsoft.com/en-us/pricing/details/blockchain-service/).

**Comment by tsaltd** [comment]
I just tried Western Europe ... no go !

No reported fixes from anyone ?

**Comment by Hakier** [comment]
Hello I have same issue:

resource group: udt-rg-internal (westeurope)
region: East US

Tested also with West Europe region and same problem :(

Any hints how to solve this problem with SKU?

**Comment by caleteeter** [comment]
Finally!!  I have a repro on this.  Sorry for the silence but I have had a heck of a time getting a setup to repro this.  I have one now and we will get this resolved!  Very sorry to those here affected!

**Comment by caleteeter** [comment]
Testing showing this working correctly now.   Closing.
